/* Recursos de rotina: metas, descanso, feedback e orientação inicial. */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n};
const day=d=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(d||''))return null;const n=new Date(d+'T12:00:00');return Number.isFinite(n.getTime())&&dataISO(n)===d?n:null};
function range(period,end){const date=day(end||hoje());const n=Number(period);if(!date)return{from:'',end:''};date.setDate(date.getDate()-Math.max(0,n-1));return{from:n?dataISO(date):'0000-01-01',end:end||hoje()}}
function activeDates(data){return [...new Set([...Object.keys(data.progresso||{}),...Object.keys(data.concluidos||{})])].filter(d=>day(d)&&d<=hoje()&&(Object.values((data.progresso||{})[d]||{}).some(a=>Array.isArray(a)&&a.length)||Object.values((data.concluidos||{})[d]||{}).some(v=>v==='manual'))).sort()}
function weekly(data,today){const end=today||hoje(),start=day(end);start.setDate(start.getDate()-((start.getDay()+6)%7));const from=dataISO(start),count=activeDates(data).filter(d=>d>=from&&d<=end).length;const target=Number(data.metas?.diasSemana);return{from,count,target:Number.isInteger(target)&&target>=1&&target<=7?target:null}}
function lastLoad(reg,today){return (Array.isArray(reg?.hist)?reg.hist:[]).filter(r=>r&&day(r.d)&&r.d<(today||hoje())&&pesosDoRegistro(r).some(v=>v!==''&&Number.isFinite(Number(v))&&Number(v)>=0)).sort((a,b)=>a.d.localeCompare(b.d)).at(-1)||null}
function parseRest(text){const s=String(text||'').trim().toLowerCase().replace(',','.');if(!s)return null;let seconds;const clock=s.match(/^(\d{1,2}):(\d{2})$/);if(clock){if(Number(clock[2])>59)return null;seconds=Number(clock[1])*60+Number(clock[2])}else{const match=s.match(/^(\d+(?:\.\d+)?)\s*(s|seg|segs|segundo|segundos|m|min|mins|minuto|minutos)?$/);if(!match)return null;seconds=Number(match[1])*(match[2]?.startsWith('m')?60:1)}return seconds>=1&&seconds<=1800?Math.round(seconds):null}
function period(){return Number($('periodoEvolucao').value)||0}
function inPeriod(d){const r=range(period());return !!day(d)&&d>=r.from&&d<=r.end}
function loadComparison(root,points){if(!points.length)return;const first=points[0],last=points.at(-1),delta=maxRegistro(last)-maxRegistro(first);root.append(el('p','routine-comparison',fmtPeso(maxRegistro(first))+' em '+fmtData(first.d)+' → '+fmtPeso(maxRegistro(last))+' em '+fmtData(last.d)+(points.length>1?' · '+(delta>0?'+':'')+fmtPeso(delta):' · Primeiro registro no período')));root.append(el('p','small-note','Até 12 pontos no gráfico. A comparação considera todos os registros do período.'))}
function renderEvolution(){const s=window.TendaEvolucao.summary(dados,hoje(),period());const box=$('resumoEvolucao');box.replaceChildren();const metrics=[['Dias com atividade no período',s.current.length],['Treinos concluídos no período',s.completed],['Exercícios com cargas no período',s.loads.length],['Última atividade',s.days.length?fmtData(s.days.at(-1)):'Sem registro']];for(const [label,value]of metrics){const row=el('div','mini-stat');row.append(el('span','',label),el('b','',value));box.append(row)}if(period())box.append(el('p','routine-comparison',s.current.length+' dias com atividade neste período e '+s.before.length+' no período anterior de '+period()+' dias.'))}
let goalFormBuilt=false;
function renderGoals(){const root=$('metasRotina');root.hidden=editando||!!sessaoAluno||(!document.body.classList.contains('modo-biblioteca')&&Object.values(dados.treinos).some(a=>a.some(e=>e.nome.trim())));if(!goalFormBuilt){const top=el('div','routine-goal-head');top.append(el('div','',null));top.firstChild.append(el('span','eyebrow','SUA SEMANA'),el('h3','','Uma rotina que cabe no seu dia.'));const status=el('strong');status.id='metaSemanaStatus';top.append(status);const details=el('details');const summary=el('summary','','Definir minhas metas');details.append(summary);const fields=el('div','routine-fields');const label=el('label');label.append(el('span','','Dias de treino por semana'));const select=el('select');select.id='metaDias';for(let i=0;i<=7;i++){const option=el('option','',i?i+' '+(i===1?'dia':'dias'):'Sem meta definida');option.value=String(i);select.append(option)}select.onchange=()=>{dados.metas=dados.metas||{};if(Number(select.value))dados.metas.diasSemana=Number(select.value);else delete dados.metas.diasSemana;salvar();renderGoals()};label.append(select);const obj=el('label');obj.append(el('span','','Meu objetivo (opcional)'));const input=el('input');input.id='metaObjetivo';input.type='text';input.maxLength=160;input.placeholder='Ex.: manter uma rotina consistente';input.oninput=()=>{dados.metas=dados.metas||{};if(input.value.trim())dados.metas.objetivo=input.value.slice(0,160);else delete dados.metas.objetivo;salvar()};obj.append(input);fields.append(label,obj);details.append(fields,el('p','small-note','A meta conta dias distintos com exercícios marcados ou treino concluído, de segunda a domingo.'));root.append(top,details);goalFormBuilt=true}
 const w=weekly(dados);$('metaSemanaStatus').textContent=w.target?w.count+' de '+w.target+' dias'+(w.count>=w.target?' · Meta alcançada':''):w.count+' dias com atividade';if(document.activeElement!==$('metaDias'))$('metaDias').value=String(w.target||0);if(document.activeElement!==$('metaObjetivo'))$('metaObjetivo').value=dados.metas?.objetivo||'';
}
let feedbackKey='',feedbackSnapshot='';
function renderFeedback(){const root=$('feedbackTreino'),key=hoje()+'|'+treinoAtual+'|'+(usuario?.uid||'guest');root.hidden=editando||!!sessaoAluno||document.body.classList.contains('modo-biblioteca')||!itens().length;const existing=dados.feedback?.[hoje()]?.[treinoAtual]||{},snapshot=JSON.stringify(existing);if(key===feedbackKey&&(snapshot===feedbackSnapshot||root.contains(document.activeElement)))return;feedbackKey=key;feedbackSnapshot=snapshot;root.open=false;const fields=$('feedbackCampos');fields.replaceChildren();
 const grid=el('div','routine-fields');function field(label,key,options){const wrap=el('label');wrap.append(el('span','',label));const select=el('select');select.id='feedback-'+key;select.append(el('option','','Não informado'));select.firstChild.value='';options.forEach(v=>{const o=el('option','',v);o.value=v;select.append(o)});select.value=existing[key]||'';select.onchange=saveFeedback;wrap.append(select);return wrap}grid.append(field('Dificuldade','dificuldade',['Leve','Moderada','Difícil']),field('Disposição','disposicao',['Baixa','Normal','Alta']));const comment=el('label');comment.append(el('span','','Comentário (opcional)'));const text=el('textarea');text.id='feedback-comentario';text.maxLength=600;text.rows=3;text.placeholder='O que você quer lembrar sobre este treino?';text.value=existing.comentario||'';text.oninput=saveFeedback;comment.append(text);const info=el('p','small-note');info.id='feedback-status';info.setAttribute('role','status');info.textContent='Registrado por dia e treino. Se tiver professor, ele poderá consultar após a sincronização.';fields.append(grid,comment,info);}
function saveFeedback(){if(editando||sessaoAluno||!itens().length)return;const value={dificuldade:$('feedback-dificuldade').value,disposicao:$('feedback-disposicao').value,comentario:$('feedback-comentario').value.slice(0,600)};dados.feedback=dados.feedback||{};dados.feedback[hoje()]=dados.feedback[hoje()]||{};if(Object.values(value).some(v=>v.trim()))dados.feedback[hoje()][treinoAtual]=value;else{delete dados.feedback[hoje()][treinoAtual];if(!Object.keys(dados.feedback[hoje()]).length)delete dados.feedback[hoje()]};feedbackSnapshot=JSON.stringify(dados.feedback?.[hoje()]?.[treinoAtual]||{});salvar();$('feedback-status').textContent=localSalvo?(usuario?'Registrado. O envio segue o status de sincronização da conta.':'Registrado neste navegador. Entre na conta para guardar na nuvem.'):'Não foi salvo neste navegador. Exporte um backup antes de fechar.'}
function renderOnboarding(){const root=$('primeirosPassos'),hasExercises=Object.values(dados.treinos).some(a=>a.some(e=>e.nome.trim())),hasLoad=Object.values(dados.pesos).some(r=>r?.hist?.some(h=>pesosDoRegistro(h).length)),hasActivity=activeDates(dados).length>0;root.hidden=!!sessaoAluno||editando||(hasExercises&&hasLoad&&hasActivity)||!document.body.classList.contains('modo-biblioteca');root.replaceChildren();if(root.hidden)return;root.append(el('span','eyebrow','PRIMEIROS PASSOS'),el('h3','','Comece com a sua rotina.'));const list=el('ol');[['Organize seu primeiro treino',hasExercises],['Registre a carga de uma série',hasLoad],['Marque um exercício realizado',hasActivity]].forEach(([text,done])=>{const item=el('li',done?'feito':'',text+(done?' ✓':''));list.append(item)});root.append(list);const b=el('button','btn',hasExercises?'Editar meus treinos':'Criar meu primeiro treino');b.type='button';b.onclick=()=>hasExercises?$('btnEditar').click():$('comecarTreino').click();root.append(b,el('p','small-note',usuario?'Seus registros usam a sincronização da conta.':'Você pode começar sem conta. Nesse caso, os registros ficam neste navegador; entre para sincronizar entre aparelhos.'))}
const timer=el('section','routine-rest');timer.id='descansoTimer';timer.hidden=true;timer.setAttribute('aria-label','Cronômetro de descanso');const caption=el('strong');caption.id='descansoNome';const display=el('output');display.id='descansoTempo';const actions=el('div','routine-rest-actions'),pause=el('button','btn','Pausar'),more=el('button','btn','+30 s'),stop=el('button','btn','Encerrar');for(const b of [pause,more,stop])b.type='button';const duration=el('label');duration.append(el('span','','Descanso padrão'));const durationSelect=el('select');durationSelect.setAttribute('aria-label','Duração padrão do descanso');for(const seconds of [30,60,90,120,180]){const o=el('option','',seconds+' s');o.value=String(seconds);durationSelect.append(o)}durationSelect.value='60';duration.append(durationSelect);const message=el('p','small-note');message.setAttribute('role','status');actions.append(pause,more,stop);timer.append(caption,display,actions,duration,message);$('lista').before(timer);
let deadline=0,remaining=0,paused=false,running=false,owner=null,training=null;
function tick(){if(!running)return;if(!paused)remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));display.textContent=Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');pause.textContent=paused?'Continuar':'Pausar';pause.disabled=remaining===0;if(remaining===0){running=false;message.textContent='Descanso concluído.';if(navigator.vibrate)navigator.vibrate(150)}}
function clearTimer(){running=false;deadline=0;remaining=0;timer.hidden=true;message.textContent=''}
function startTimer(ex){owner=usuario?.uid||'guest';training=treinoAtual;remaining=parseRest(ex.descanso)||Number(durationSelect.value);deadline=Date.now()+remaining*1000;paused=false;running=true;caption.textContent='Descanso · '+ex.nome;message.textContent=ex.descanso&&!parseRest(ex.descanso)?'Tempo do plano não reconhecido. Usando o descanso padrão.':'';timer.hidden=false;tick();timer.scrollIntoView({block:'nearest',behavior:'smooth'})}
pause.onclick=()=>{if(!running)return;if(!paused){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));paused=true}else{deadline=Date.now()+remaining*1000;paused=false}tick()};more.onclick=()=>{remaining=Math.min(1800,(running&&!paused?Math.max(0,Math.ceil((deadline-Date.now())/1000)):remaining)+30);deadline=Date.now()+remaining*1000;running=true;message.textContent='';tick()};stop.onclick=clearTimer;
setInterval(tick,1000);document.addEventListener('visibilitychange',tick);
function restButton(ex){const b=el('button','busca-ex','Descansar'+(parseRest(ex.descanso)?' · '+parseRest(ex.descanso)+' s':''));b.type='button';b.setAttribute('aria-label','Iniciar descanso após '+ex.nome);b.onclick=()=>startTimer(ex);return b}
const originalRender=render;render=function(){originalRender();const current=usuario?.uid||'guest';if(owner!==current||training!==treinoAtual||editando||document.body.classList.contains('modo-biblioteca'))clearTimer();renderGoals();renderFeedback();renderOnboarding()};
const originalPanel=atualizarPainel;atualizarPainel=function(){originalPanel();renderGoals()};
const oldApply=aplicarSync;aplicarSync=function(c){oldApply(c);renderFeedback()};
const oldAccount=atualizaBotaoConta;let lastOwner=usuario?.uid||'guest';atualizaBotaoConta=function(){oldAccount();const current=usuario?.uid||'guest';if(current!==lastOwner){clearTimer();feedbackKey='';lastOwner=current;}renderGoals();renderFeedback();renderOnboarding()};
const oldSafe=window.tendaAtualizacaoSegura;window.tendaAtualizacaoSegura=()=>!running&&oldSafe();
const oldUpdate=window.tendaPodeAtualizar;window.tendaPodeAtualizar=async()=>{if(running){mostrarStatus('Encerre o descanso antes de atualizar o aplicativo.');return false}return oldUpdate()};
$('periodoEvolucao').onchange=renderEvolucao;
window.TendaRotina={range,weekly,activeDates,lastLoad,parseRest,inPeriod,loadComparison,renderEvolution,restButton};
render();
})();
